spring:
  jmx:
    enabled: false
  application:
    name: "N26-Transactions-Statistics"

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      base-path: '/n26-secured'
      exposure:
        include: 'info,health'
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    info:
      enabled: true
      show-details: ALWAYS
      git:
        enabled: true
        mode: full
    metrics:
      enabled: true
      show-details: ALWAYS
info:
  app:
    name: N26-Transactions-Statistics
    description: Developed by Ankur Malik
    version: 1.0.0

statistics:
  milliseconds-to-consider: 60000
